KidKinder/Entities/About.cs
namespace KidKinder.Entities
{
    public class About
    {
        public int AboutId { get; set; }
        public string BigImageUrl { get; set; }
        public string Header { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string SmallImageUrl { get; set; }

    }
}

KidKinder/Entities/AboutList.cs
namespace KidKinder.Entities
{
    public class AboutList
    {
        public int AboutListId { get; set; }
        public string Description { get; set; }
    }
}

KidKinder/Entities/Address.cs
namespace KidKinder.Entities
{
    public class Address
    {
        public int AddressId { get; set; }
        public string Description { get; set; }
        public string AddressDetail { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string OpeningHours { get; set; }
    }
}

KidKinder/Entities/Admin.cs
namespace KidKinder.Entities
{
    public class Admin
    {
        public int AdminId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

KidKinder/Entities/BookASeat.cs
namespace KidKinder.Entities
{
    public class BookASeat
    {
        public int BookASeatId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int ClassCategory { get; set; }


    }
}

KidKinder/Entities/Branch.cs
using System.Collections.Generic;

namespace KidKinder.Entities
{
    public class Branch
    {
        public int BranchId { get; set; }
        public string BranchName { get; set; }
        public List<Teacher> Teachers { get; set; } // Bire çok ilişki

    }
}

KidKinder/Entities/ClassRoom.cs
namespace KidKinder.Entities
{
    public class ClassRoom
    {
        public int ClassRoomId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string AgeofKids { get; set; }
        public byte TotalSeats { get; set; }
        public string ClassTime { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }



    }
}

KidKinder/Entities/Communication.cs
namespace KidKinder.Entities
{
    public class Communication
    {
        public int CommunicationId { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    }
}

KidKinder/Entities/Contact.cs
using System;

namespace KidKinder.Entities
{
    public class Contact
    {
        public int ContactID { get; set; }
        public string NameSurname { get; set; }
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public DateTime SendDate { get; set; }
        public bool IsRead { get; set; }
    }
}

KidKinder/Entities/Feature.cs
namespace KidKinder.Entities
{
    public class Feature
    {
        public int FeatureId { get; set; }
        public string Title { get; set; }
        public string Header { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }

    }
}

KidKinder/Entities/Gallery.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KidKinder.Entities
{
    public class Gallery
    {
        public int GalleryId { get; set; }
        public string ImageUrl { get; set; }
        public bool Status { get; set; }
    }
}

KidKinder/Entities/MailSubscribe.cs
namespace KidKinder.Entities
{
    public class MailSubscribe
    {
        public int MailSubscribeId { get; set; }
        public string NameSurname { get; set; }
        public string Email { get; set; }
    }
}

KidKinder/Entities/Notification.cs
using System;

namespace KidKinder.Entities
{
    public class Notification
    {
        public int NotificationId { get; set; }
        public string Title { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
        public DateTime NotificationDate { get; set; }
    }
}

KidKinder/Entities/Service.cs
namespace KidKinder.Entities
{
    public class Service
    {
        public int ServiceId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string IconUrl { get; set; }

    }
}

KidKinder/Entities/SocialMedia.cs
namespace KidKinder.Entities
{
    public class SocialMedia
    {
        public int SocialMediaId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
    }
}

KidKinder/Entities/Teacher.cs
namespace KidKinder.Entities
{
    public class Teacher
    {
        public int TeacherId { get; set; }
        public string NameSurname { get; set; }
        public string ImageUrl { get; set; }
        public int BranchId { get; set; }
        public virtual Branch Branch { get; set; } // Bire çok ilişki
    }
}

KidKinder/Entities/Testimonial.cs
namespace KidKinder.Entities
{
    public class Testimonial
    {
        public int TestimonialId { get; set; }
        public string ImageUrl { get; set; }
        public string NameSurname { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
    }
}

KidKinder/Models/TeacherViewModel.cs
namespace KidKinder.Models
{
    public class TeacherViewModel
    {
        public string TeacherNameSurname { get; set; }
        public string TeacherTitle { get; set; }
        public string TeacherImageUrl { get; set; }

    }
}

KidKinder/Controllers/AboutController.cs
using KidKinder.Context;
using System.Linq;
using System.Web.Mvc;

namespace KidKinder.Controllers
{

    public class AboutController : Controller
    {
        KidKinderContext context = new KidKinderContext();
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult AboutHeaderPartial()
        {
            return PartialView();
        }
        public PartialViewResult AboutIndexPartial()
        {
            var values = context.Abouts.ToList();
            return PartialView(values);
        }
    }
}

KidKinder/Controllers/AdminLayoutController.cs
using KidKinder.Context;
using System.Linq;
using System.Web.Mvc;

namespace KidKinder.Controllers
{

    public class AdminLayoutController : Controller
    {
        KidKinderContext context = new KidKinderContext();
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult PartialHead()
        {
            return PartialView();
        }

        public PartialViewResult PartialPreLoader()
        {
            return PartialView();
        }

        public PartialViewResult PartialNavbar()
        {
            return PartialView();
        }
        public PartialViewResult PartialNotification()
        {
            var values = context.Notifications.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialNavbarProfileHeader()
        {
            return PartialView();
        }
        public PartialViewResult PartialSidebar()
        {
            return PartialView();
        }

        public PartialViewResult PartialScripts()
        {
            return PartialView();
        }
        public PartialViewResult PartialHeader()
        {
            return PartialView();
        }
    }
}

KidKinder/Controllers/HomeController.cs
using System.Web.Mvc;

namespace KidKinder.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

KidKinder/Views/AdminLayout/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

@Html.Action("PartialHead", "AdminLayout")

<body>
    <!-- Pre-loader start -->
    @Html.Action("PartialPreLoader", "AdminLayout")
    <!-- Pre-loader end -->
    <div id="pcoded" class="pcoded">
        <div class="pcoded-overlay-box"></div>
        <div class="pcoded-container navbar-wrapper">

            @Html.Action("PartialNavbar", "AdminLayout")

            <div class="pcoded-main-container">
                <div class="pcoded-wrapper">
                    @Html.Action("PartialSidebar", "AdminLayout")
                    <div class="pcoded-content">

                        @Html.Action("PartialHeader", "AdminLayout")

                        @RenderBody()

                    </div>
                    <div id="styleSelector"></div>
                </div>
            </div>
        </div>
    </div>

    @Html.Action("PartialScripts", "AdminLayout")
</body>

</html>

KidKinder/Views/AdminLayout/PartialHead.cshtml
<head>
    <title>KidKinder Admin Paneli</title>

    <!-- Favicon icon -->
    <link rel="icon" href="~/Templates/material_able-main/assets/images/favicon.ico" type="image/x-icon">
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <!-- Required Fremwork -->
    <link rel="stylesheet" type="text/css" href="~/Templates/material_able-main/assets/css/bootstrap/css/bootstrap.min.css">
    <!-- waves.css -->


    <link rel="stylesheet" href="~/Templates/material_able-main/assets/pages/waves/css/waves.min.css" type="text/css" media="all">
    <!-- themify-icons line icon -->
    <link rel="stylesheet" type="text/css" href="~/Templates/material_able-main/assets/icon/themify-icons/themify-icons.css">
    <!-- feather icon -->
    <link rel="stylesheet" type="text/css" href="~/Templates/material_able-main/assets/icon/feather/css/feather.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" type="text/css" href="~/Templates/material_able-main/assets/icon/font-awesome/css/font-awesome.min.css">
    <!-- Style.css -->
    <link rel="stylesheet" type="text/css" href="~/Templates/material_able-main/assets/css/style.css">
    <link rel="stylesheet" type="text/css" href="~/Templates/material_able-main/assets/css/jquery.mCustomScrollbar.css">

</head>

KidKinder/Views/AdminLayout/PartialHeader.cshtml
<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h5 class="m-b-10">Basic Form Inputs</h5>
                    <p class="m-b-0">Lorem Ipsum is simply dummy text of the printing</p>
                </div>
            </div>
            <div class="col-md-4">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html"> <i class="fa fa-home"></i> </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Öğretmenler</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Yeni Öğretmen Girişi</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

KidKinder/Views/AdminLayout/PartialNavbar.cshtml
<nav class="navbar header-navbar pcoded-header">
    <div class="navbar-wrapper">
        <div class="navbar-logo">
            <a class="mobile-menu waves-effect waves-light" id="mobile-collapse" href="#!">
                <i class="ti-menu"></i>
            </a>
            <div class="mobile-search waves-effect waves-light">
                <div class="header-search">
                    <div class="main-search morphsearch-search">
                        <div class="input-group">
                            <span class="input-group-prepend search-close"><i class="ti-close input-group-text"></i></span>
                            <input type="text" class="form-control" placeholder="Enter Keyword">
                            <span class="input-group-append search-btn"><i class="ti-search input-group-text"></i></span>
                        </div>
                    </div>
                </div>
            </div>
            <a href="index.html">
               <img class="img-fluid" width="50" src="~/Templates/material_able-main/assets/images/alphabet-blocks.png" alt="Theme-Logo" />
            </a>
            <a class="mobile-options waves-effect waves-light">
                <i class="ti-more"></i>
            </a>
        </div>
        <div class="navbar-container container-fluid">
            <ul class="nav-left">
                <li>
                    <div class="sidebar_toggle"><a href="javascript:void(0)"><i class="ti-menu"></i></a></div>
                </li>
                <li>
                    <a href="#!" onclick="javascript:toggleFullScreen()" class="waves-effect waves-light">
                        <i class="ti-fullscreen"></i>
                    </a>
                </li>
            </ul>
            <ul class="nav-right">
                @Html.Action("PartialNotification", "AdminLayout")
                @Html.Action("PartialNavbarProfileHeader", "AdminLayout")
            </ul>
        </div>
    </div>
</nav>

KidKinder/Views/AdminLayout/PartialNavbarProfileHeader.cshtml
<li class="user-profile header-notification">
    <a href="#!" class="waves-effect waves-light">
        <img src="~/Templates/material_able-main/assets/images/avatar-4.jpg" class="img-radius" alt="User-Profile-Image">
        <span>John Doe</span>
        <i class="ti-angle-down"></i>
    </a>
    <ul class="show-notification profile-notification">
        <li class="waves-effect waves-light">
            <a href="#!">
                <i class="ti-settings"></i> Ayarlar
            </a>
        </li>
        <li class="waves-effect waves-light">
            <a href="user-profile.html">
                <i class="ti-user"></i> Profilim
            </a>
        </li>
        <li class="waves-effect waves-light">
            <a href="email-inbox.html">
                <i class="ti-email"></i> Mesajlar
            </a>
        </li>
        <li class="waves-effect waves-light">
            <a href="auth-lock-screen.html">
                <i class="ti-lock"></i> Ekranı Kilitle
            </a>
        </li>
        <li class="waves-effect waves-light">
            <a href="/Login/AdminLogin/">
                <i class="ti-layout-sidebar-left"></i> Çıkış Yap
            </a>
        </li>
    </ul>
</li>

KidKinder/Views/AdminLayout/PartialNotification.cshtml
@model List<KidKinder.Entities.Notification>

<li class="header-notification">
    <a href="#!" class="waves-effect waves-light">
        <i class="ti-bell"></i>
        <span class="badge bg-c-red"></span>
    </a>
    <ul class="show-notification">
        <li>
            <h6>Bildirimler</h6>
            <label class="label label-danger">Yeni</label>
        </li>
        @foreach(var item in Model)
        {
        <li class="waves-effect waves-light">
            <div class="media">
                <img class="d-flex align-self-center img-radius" src="@item.ImageUrl" alt="Generic placeholder image">
                <div class="media-body">
                    <h5 class="notification-user">@item.Title</h5>
                    <p class="notification-msg">@item.Description</p>
                    <span class="notification-time">@item.NotificationDate.ToShortDateString()</span>
                </div>
            </div>
        </li>
        }
    </ul>
</li>

KidKinder/Views/AdminLayout/PartialPreLoader.cshtml
<div class="theme-loader">
    <div class="loader-track">
        <div class="preloader-wrapper">
            <div class="spinner-layer spinner-blue">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="gap-patch">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
            <div class="spinner-layer spinner-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="gap-patch">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
            <div class="spinner-layer spinner-yellow">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="gap-patch">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
            <div class="spinner-layer spinner-green">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="gap-patch">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
    </div>
</div>

KidKinder/Views/AdminLayout/PartialScripts.cshtml
<!-- Required Jquery -->
<script type="text/javascript" src="~/Templates/material_able-main/assets/js/jquery/jquery.min.js "></script>
<script type="text/javascript" src="~/Templates/material_able-main/assets/js/jquery-ui/jquery-ui.min.js "></script>
<script type="text/javascript" src="~/Templates/material_able-main/assets/js/popper.js/popper.min.js"></script>
<script type="text/javascript" src="~/Templates/material_able-main/assets/js/bootstrap/js/bootstrap.min.js "></script>


<!-- waves js -->
<script src="~/Templates/material_able-main/assets/pages/waves/js/waves.min.js"></script>


<!-- jquery slimscroll js -->
<script type="text/javascript" src="~/Templates/material_able-main/assets/js/jquery-slimscroll/jquery.slimscroll.js"></script>
<script src="~/Templates/material_able-main/assets/js/pcoded.min.js"></script>
<script src="~/Templates/material_able-main/assets/js/vertical/vertical-layout.min.js"></script>
<script src="~/Templates/material_able-main/assets/js/jquery.mCustomScrollbar.concat.min.js"></script>
<!-- Custom js -->
<script type="text/javascript" src="~/Templates/material_able-main/assets/js/script.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>﻿

KidKinder/Views/AdminLayout/PartialSidebar.cshtml
<nav class="pcoded-navbar">
    <div class="sidebar_toggle"><a href="#"><i class="icon-close icons"></i></a></div>
    <div class="pcoded-inner-navbar main-menu">
        <div class="">
            <div class="main-menu-header">
                <img class="img-80 img-radius" src="~/Templates/material_able-main/assets/images/avatar-4.jpg" alt="User-Profile-Image">
                <div class="user-details">
                    <span id="more-details">KidKinder Admin</span>
                </div>
            </div>
        </div>
        <ul class="pcoded-item pcoded-left-item">
            <li class="">
                <a href="/Default/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-home"></i><b>D</b></span>
                    <span class="pcoded-mtext">Anasayfa</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/Dashboard/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-home"></i><b>D</b></span>
                    <span class="pcoded-mtext">Dashboard</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/Class/ClassList/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-home"></i><b>D</b></span>
                    <span class="pcoded-mtext">Sınıflar</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/Teacher/TeacherList" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-home"></i><b>D</b></span>
                    <span class="pcoded-mtext">Öğretmenler</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/Service/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-home"></i><b>D</b></span>
                    <span class="pcoded-mtext">Hizmetler</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/GaleriAdmin/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-home"></i><b>D</b></span>
                    <span class="pcoded-mtext">Galeri</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/Message/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-home"></i><b>D</b></span>
                    <span class="pcoded-mtext">Gelen Mesajlar</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/Testimonial/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-home"></i><b>D</b></span>
                    <span class="pcoded-mtext">Referanslar</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/Testimonial/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-home"></i><b>D</b></span>
                    <span class="pcoded-mtext">Çıkış Yap</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
        </ul>
    </div>
</nav>