KidKinder/Entities/ClassRoom.cs
namespace KidKinder.Entities
{
    public class ClassRoom
    {
        public int ClassRoomId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string AgeofKids { get; set; }
        public byte TotalSeats { get; set; }
        public string ClassTime { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }



    }
}

KidKinder/Controllers/ClassRoomController.cs
using KidKinder.Context;
using System.Linq;
using System.Web.Mvc;

namespace KidKinder.Controllers
{
    public class ClassRoomController : Controller
    {
        KidKinderContext context = new KidKinderContext();
        public ActionResult Index()
        {
            var values = context.ClassRooms.ToList();
            return View(values);
        }
        public PartialViewResult ClassRoomHeaderPartial()
        {
            return PartialView();
        }
    }
}

KidKinder/Views/ClassRoom/ClassRoomHeaderPartial.cshtml
<div class="container-fluid bg-primary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center"
         style="min-height: 400px">
        <h3 class="display-3 font-weight-bold text-white">Classroom</h3>
        <div class="d-inline-flex text-white">
            <p class="m-0"><a class="text-white" href="">Ana Sayfa</a></p>
            <p class="m-0 px-2">/</p>
            <p class="m-0">Classroom</p>
        </div>
    </div>
</div>

KidKinder/Views/ClassRoom/Index.cshtml
@model List<KidKinder.Entities.ClassRoom>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AnaLayout.cshtml";
}

@Html.Action("ClassRoomHeaderPartial", "ClassRoom")

<div class="container-fluid pt-5" id="class">
    <div class="container">
        <div class="text-center pb-2">
            <p class="section-title px-5">
                <span class="px-2">POPÜLER EĞİTİM SINIFLARIMIZ</span>
            </p>
            <h1 class="mb-4">Çocuğunuz İçin Grubu Seçin</h1>
        </div>


        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 mb-5">
                    <div class="card border-0 bg-light shadow-sm pb-2">
                        <img class="card-img-top mb-2" src="@item.ImageUrl" alt="" height="200" width="150" />
                        <div class="card-body text-center">
                            <h4 class="card-title">@item.Title</h4>
                            <p class="card-text">
                                @item.Description
                            </p>
                        </div>
                        <div class="card-footer bg-transparent py-4 px-5">
                            <div class="row border-bottom">
                                <div class="col-6 py-1 text-right border-right">
                                    <strong>Yaş Aralığı</strong>
                                </div>
                                <div class="col-6 py-1">@item.AgeofKids</div>
                            </div>
                            <div class="row border-bottom">
                                <div class="col-6 py-1 text-right border-right">
                                    <strong>Kontenjan</strong>
                                </div>
                                <div class="col-6 py-1">@item.TotalSeats</div>
                            </div>
                            <div class="row border-bottom">
                                <div class="col-6 py-1 text-right border-right">
                                    <strong>Ders Saatleri</strong>
                                </div>
                                <div class="col-6 py-1">@item.ClassTime</div>
                            </div>
                            <div class="row">
                                <div class="col-6 py-1 text-right border-right">
                                    <strong>Fiyat</strong>
                                </div>
                                <div class="col-6 py-1">@item.Price /Aylık</div>
                            </div>
                        </div>
                        <a href="" class="btn btn-primary px-4 mx-auto mb-4">Şimdi Kaydol</a>
                    </div>

                </div>
            }

        </div>

    </div>
</div>